name: NestJS test, build and deploy
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverage

  e2e:
    runs-on: ubuntu-latest
    container: node:16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile

      - name: Connect to Postgres
        run: node check-postgres.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: postgres
          POSTGRES_PORT: 5432

      - name: E2E Tests
        run: yarn test:e2e --coverage
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: postgres
          POSTGRES_PORT: 5432

  deploy:
    needs: [test, e2e]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn create-db-config
        env:
          POSTGRES_HOST: /cloudsql/workoutz:europe-west3:workoutz
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: "${{ secrets.GCLOUD_POSTGRES_PASSWORD }}"
          POSTGRES_PORT: 5432
      - run: yarn build
      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v0"
      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
